### PR TITLE
Added PDFs to the bottom; added Slack link at the top; …

### PR DESCRIPTION
**Pull request by skylenewman**
made more responsive-y by using tweaking Bootstrap columns and adding 'hidden-xs' classes to extra information or formatting `<br>s` for larger screens. Updated FontAwesome to get fa-file-pdf-o for the downloads. Used `<u>` to make the DOWNLOAD link look like a link.

### CODE REVIEW

**Comment by chadxz** [comment]
LGTM, although it helps to post screenshots in your pr for stylistic changes like this so that people can see without needing to compile and run

**Comment by chadxz** [comment]
the pdf icons aren't showing properly for me.

screen shot 2015-07-15 at 8 05 11 am

**Comment by chadxz** [comment]
i'm not crazy about the individual downloads having such a large presence on the page. it won't really scale well, and looks weird.

screen shot 2015-07-15 at 8 08 18 am

**Comment by chadxz** [comment]
all that being said, i think it'd be fine to iterate on the look and feel as time goes on, and having it like this would be fine for now (once the pdf icons are fixed)

**Comment by skylenewman** [comment]
Those should just be FontAwesome icons. I tested only on Chrome on Mint. I
will check others, fix and resubmit.

I thought about having a separate page, but thought that would be overkill
for two files.

**Comment by chadxz** [comment]
Yeah i'm not a fan of a separate page either. I don't really have a good suggestion on how to make it better at the moment :(

**Comment by chadxz** [comment]
RE: icons missing, I just cloned the repo and did `open index.html` on my mac. I also tried viewing it via rawgit: http://cdn.rawgit.com/skylenewman/hackhuntsville.github.io/master/index.html

**Comment by chadxz** [comment]
oh. looks like you need to update the font file as well (the woff). You had only updated the css file. And it looks like it's looking for a "woff2" file now as well, so you may wanna include that too.

**Comment by skylenewman** [comment]
Maybe my system had cached the font? I saw the icon on the link supplied
before I updated.

###
Kyle Newman
Software and Website Design and Development
cell: 205.270.9230

**Comment by skylenewman** [comment]
hh-web-pr-3-1
hh-web-pr-3-2
hh-web-pr-3-3
hh-web-pr-3-4
hh-web-pr-3-5
hh-web-pr-3-6

**Pull request closed without merging**
